ALTER TABLE dim_date_times 
ALTER COLUMN month TYPE VARCHAR(30),
ALTER COLUMN year TYPE VARCHAR(30),
ALTER COLUMN day TYPE VARCHAR(30),
ALTER COLUMN time_period TYPE VARCHAR(40),
ALTER COLUMN date_uuid TYPE uuid USING date_uuid::uuid;