UPDATE dim_currency
SET currency_conversion_key = dim_currency_conversion.currency_conversion_key
FROM dim_currency_conversion
WHERE dim_currency.currency_code = dim_currency_conversion.currency_code;